### ISSUE TITLE
ModuleNotFoundError: No module named 'base_agent'

### ISSUE THREAD

**Issue by 837liu** [facebookresearch/craftassist#32]
I'm on an Ubuntu 18.04 system.

In both the Docker and the local setup, when I get to this part:

_python ./python/craftassist/craftassist_agent.py_

I get the same stack dump:

_root@1706ae62edc6:/craftassist# python ./python/craftassist/craftassist_agent.pyTraceback (most recent call last):
  File "./python/craftassist/craftassist_agent.py", line 21, in <module>
    import mc_memory
  File "/craftassist/python/craftassist/mc_memory.py", line 10, in <module>
    import dance
  File "/craftassist/python/craftassist/dance.py", line 8, in <module>
    import tasks
  File "/craftassist/python/craftassist/tasks.py", line 17, in <module>
    import search
  File "/craftassist/python/craftassist/search.py", line 11, in <module>
    import util
  File "/craftassist/python/craftassist/util.py", line 16, in <module>
    import base_agent.rotation as rotation
ModuleNotFoundError: No module named 'base_agent'_

I'll try on a Docker for Windows environment next to see if it's reproducible there as well.

**Comment by 837liu** [comment]
Replicated the error on Dockers for Window on a Win10 system.

**Comment by 837liu** [comment]
Adding:

_import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)_ 

to _python/craftassist/base_agent/util.py_ so that _util.py_ can import from _base_agent_ a level up seems to have fixed the problem, but I don't know the code structure well enough to know if this is an appropriate fix.

**Comment by markperez1904** [comment]
I'm also getting the same error on Ubuntu 18.04, but I'm unable to implement the workaround from @837liu because for me, the `util.py` file is actually under `/craftassist/python/base_agent`.

Regardless, adding the 4 lines of python code didn't resolve this.

**Comment by snyxan** [comment]
Hi @837liu & @markperez1904,

Thanks for pointing this out! We've fixed this bug in #33. 

The issue is automatically closed after the PR is merged. But please try it out and feel free to post any relevant questions if any.
