### ISSUE TITLE
Heuristic perception error

### ISSUE THREAD

**Issue by snyxan** [facebookresearch/craftassist#46]
```
2020-10-02 00:08:57,790 [mc_memory_nodes.py:131 - create() INFO]: Added block object 42d74585276d4e879d46b3cd9087211a with 1 blocks, Counter({(30, 0): 1})
2020-10-02 00:08:57,824 [mc_memory_nodes.py:131 - create() INFO]: Added block object 4e4b5f267f894f9484ee6e93f509fd0c with 1 blocks, Counter({(50, 4): 1})
2020-10-02 00:09:26,580 [loco_mc_agent.py:81 - handle_exception() ERROR]: Default handler caught exception, db_log_idx=115013
Traceback (most recent call last):
  File "/private/home/yuxuans/Workspace/tmp/craftassist/python/craftassist/../base_agent/core.py", line 18, in start
    self.step()
  File "/private/home/yuxuans/Workspace/tmp/craftassist/python/craftassist/../base_agent/loco_mc_agent.py", line 93, in step
    super().step()
  File "/private/home/yuxuans/Workspace/tmp/craftassist/python/craftassist/../base_agent/core.py", line 23, in step
    self.perceive()
  File "python/craftassist/craftassist_agent.py", line 113, in perceive
    v.perceive(force=force)
  File "/private/home/yuxuans/Workspace/tmp/craftassist/python/craftassist/heuristic_perception.py", line 522, in perceive
    get_nearby_airtouching_blocks(self.agent, pos, radius)
  File "/private/home/yuxuans/Workspace/tmp/craftassist/python/craftassist/heuristic_perception.py", line 363, in get_nearby_airtouching_blocks
    yzxb = agent.get_blocks(x - radius, x + radius, ymin, y + radius, z - radius, z + radius)
ValueError: vector::_M_default_append
2020-10-02 00:09:26,586 [craftassist_agent.py:235 - send_chat() INFO]: Sending chat: Oops! I got confused and wasn't able to complete my last task :(
```

**Comment by kavyasrinet** [comment]
@snyxan checking in if you meant to create this issue in the public repo ?

**Comment by hepengfe** [comment]
Hi yuxuan, I got the same problem. Is it fixed yet?  @snyxan

**Comment by snyxan** [comment]
Hi @feipenghe,

It's WIP. Could you please post: 1. full traceback of the error, 2. the command you just gave and 3. few lines of logs related to the task the agent was executing so we can better understand your case?
