### ISSUE TITLE
When running 'cuberite_process.py' get "SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by MrAusnadian** [facebookresearch/craftassist#7]
make command completes successfully, however, I receive SyntaxError when attemping to run the process:
```
will@Bedroom:~/craftassist$ python ./python/cuberite_process.py
Traceback (most recent call last):
  File "./python/cuberite_process.py", line 19, in <module>
    from craftassist.shape_helpers import build_shape_scene
  File "/home/will/craftassist/python/craftassist/shape_helpers.py", line 9, in <module>
    import shapes
  File "/home/will/craftassist/python/craftassist/shapes.py", line 22
    size: Tuple[int, int] = (5, 3),
        ^
SyntaxError: invalid syntax
```

make output:
```
will@Bedroom:~/craftassist$ make
cd cuberite && \
mkdir -p Release && \
cd Release && \
cmake -DCMAKE_BUILD_TYPE=RELEASE .. && \
make -j`nproc`
-- Lua has NOT been found in your system, the build will use its own Lua implementation.
-- JsonCpp Version: 1.6.4
-- SQLITECPP_RUN_CPPLINT OFF
-- SQLITECPP_RUN_CPPCHECK OFF
-- SQLITECPP_RUN_DOXYGEN OFF
-- SQLITECPP_BUILD_EXAMPLES OFF
-- SQLITECPP_BUILD_TESTS OFF
--
--         ---( Libevent 2.1.8-beta )---
--
-- Available event backends:
-- CMAKE_BINARY_DIR:         /home/will/craftassist/cuberite/Release
-- CMAKE_CURRENT_BINARY_DIR: /home/will/craftassist/cuberite/Release/lib/libevent
-- CMAKE_SOURCE_DIR:         /home/will/craftassist/cuberite
-- CMAKE_CURRENT_SOURCE_DIR: /home/will/craftassist/cuberite/lib/libevent
-- PROJECT_BINARY_DIR:       /home/will/craftassist/cuberite/Release/lib/libevent
-- PROJECT_SOURCE_DIR:       /home/will/craftassist/cuberite/lib/libevent
-- CMAKE_MODULE_PATH:        /home/will/craftassist/cuberite/lib/libevent/cmake/
-- CMAKE_COMMAND:            /usr/bin/cmake
-- CMAKE_ROOT:               /usr/share/cmake-3.10
-- CMAKE_SYSTEM:             Linux-4.4.0-18970-Microsoft
-- CMAKE_SYSTEM_NAME:        Linux
-- CMAKE_SYSTEM_VERSION:     4.4.0-18970-Microsoft
-- CMAKE_SYSTEM_PROCESSOR:   x86_64
-- CMAKE_SKIP_RPATH:         NO
-- CMAKE_VERBOSE_MAKEFILE:   FALSE
-- CMAKE_C_FLAGS:               -pthread   -fsigned-char -Wall -Wswitch -fno-strict-aliasing
-- CMAKE_BUILD_TYPE:         RELEASE
-- CMAKE_C_COMPILER:         /usr/bin/cc
-- CMAKE_AR:                 /usr/bin/ar
-- CMAKE_RANLIB:             /usr/bin/ranlib
--
-- CMake version: 3.10.2
-- Version: 4.1.1
-- Build type: RELEASE
including mbedtls
Can't open perl script "/home/will/craftassist/cuberite/scripts/config.pl": No such file or directory
-- Configuring done
-- Generating done
-- Build files have been written to: /home/will/craftassist/cuberite/Release
make[1]: Entering directory '/home/will/craftassist/cuberite/Release'
make[2]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
[  1%] Built target jsoncpp_lib_static
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
[  5%] Built target zlib
[ 11%] Built target lua
[ 12%] Built target SQLiteCpp
[ 13%] Built target expat
[ 14%] Built target fmt
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
[ 24%] Built target event_extra
[ 24%] Built target event_core
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
[ 34%] Built target mbedcrypto
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
[ 34%] Built target luaexe
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
[ 34%] Built target luaexpat
[ 35%] Built target tolualib
[ 35%] Built target sqlite
[ 38%] Built target OSSupport
[ 42%] Built target HTTPServer
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
[ 42%] Built target Items
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
[ 45%] Built target Blocks
[ 45%] Built target Protocol
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
[ 52%] Built target Simulator
[ 54%] Built target Mobs
[ 54%] Built target IncrementalRedstoneSimulator
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
[ 58%] Built target BlockEntities
[ 60%] Built target Noise
[ 63%] Built target UI
[ 65%] Built target mbedx509
[ 67%] Built target WorldStorage
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
[ 69%] Built target mbedtls
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
[ 74%] Built target Entities
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
[ 77%] Built target mbedTLS++
[ 81%] Built target Bindings
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
[ 87%] Built target Generating
make[3]: Entering directory '/home/will/craftassist/cuberite/Release'
make[3]: Leaving directory '/home/will/craftassist/cuberite/Release'
[100%] Built target Cuberite
make[2]: Leaving directory '/home/will/craftassist/cuberite/Release'
make[1]: Leaving directory '/home/will/craftassist/cuberite/Release'
cd client && \
cmake . && \
make
-- pybind11 v2.3.dev0
CMake Warning (dev) at CMakeLists.txt:19 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "agent".  All uses of target_link_libraries with a target should
  be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * pybind11/tools/pybind11Tools.cmake:107 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/will/craftassist/client
make[1]: Entering directory '/home/will/craftassist/client'
make[2]: Entering directory '/home/will/craftassist/client'
make[3]: Entering directory '/home/will/craftassist/client'
make[3]: Leaving directory '/home/will/craftassist/client'
[100%] Built target agent
make[2]: Leaving directory '/home/will/craftassist/client'
make[1]: Leaving directory '/home/will/craftassist/client'
g++ -std=c++17 -Wall -Wextra -Werror -O3 \
        client/src/block_map.cpp client/src/game_state.cpp client/src/graphics.cpp client/src/packet_writer.cpp client/src/types.cpp client/src/util.cpp client/src/nbt_tag.cpp logging/src/anvil_reader.cpp logging/src/logging_reader.cpp logging/src/log_render.cpp \
        -o bin/log_render \
        -lglog -lgflags -lz -pthread
g++ -std=c++17 -Wall -Wextra -Werror -O3 \
        client/src/block_map.cpp client/src/game_state.cpp client/src/graphics.cpp client/src/packet_writer.cpp client/src/types.cpp client/src/util.cpp client/src/nbt_tag.cpp logging/src/anvil_reader.cpp logging/src/logging_reader.cpp logging/src/render_view.cpp \
        -o bin/render_view \
        -lglog -lgflags -lz -pthread
g++ -std=c++17 -Wall -Wextra -Werror -O3 \
        client/src/block_map.cpp client/src/game_state.cpp client/src/graphics.cpp client/src/packet_writer.cpp client/src/types.cpp client/src/util.cpp client/src/nbt_tag.cpp \
        schematic_convert/src/schematic_convert.cpp \
        -o bin/schematic_convert \
        -lglog -lgflags -lz -pthread
```

test.sh output:
```
will@Bedroom:~/craftassist$ ./python/craftassist/test.sh
EEEEEEEEEEE
======================================================================
ERROR: dialogue_objects (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: dialogue_objects
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/dialogue_objects/__init__.py", line 1, in <module>
    from .interpreter import Interpreter
  File "/home/will/craftassist/python/craftassist/dialogue_objects/interpreter.py", line 6, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


======================================================================
ERROR: test.test_agent (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_agent
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/test/test_agent.py", line 7, in <module>
    from craftassist_agent import CraftAssistAgent
  File "/home/will/craftassist/python/craftassist/craftassist_agent.py", line 14, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


======================================================================
ERROR: test.test_coref_resolve (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_coref_resolve
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/test/test_coref_resolve.py", line 7, in <module>
    import shapes
  File "/home/will/craftassist/python/craftassist/shapes.py", line 8, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


======================================================================
ERROR: test.test_dialogue_objects (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_dialogue_objects
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/test/test_dialogue_objects.py", line 8, in <module>
    import tasks
  File "/home/will/craftassist/python/craftassist/tasks.py", line 6, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


======================================================================
ERROR: test.test_get_memory (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_get_memory
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/test/test_get_memory.py", line 7, in <module>
    import shapes
  File "/home/will/craftassist/python/craftassist/shapes.py", line 8, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


======================================================================
ERROR: test.test_interpreter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_interpreter
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/test/test_interpreter.py", line 8, in <module>
    import perception
  File "/home/will/craftassist/python/craftassist/perception.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


======================================================================
ERROR: test.test_memory (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_memory
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/test/test_memory.py", line 7, in <module>
    import shapes
  File "/home/will/craftassist/python/craftassist/shapes.py", line 8, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


======================================================================
ERROR: test.test_put_memory (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_put_memory
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/test/test_put_memory.py", line 7, in <module>
    import shapes
  File "/home/will/craftassist/python/craftassist/shapes.py", line 8, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


======================================================================
ERROR: test.test_size_words (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_size_words
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/test/test_size_words.py", line 7, in <module>
    import size_words
  File "/home/will/craftassist/python/craftassist/size_words.py", line 8, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


======================================================================
ERROR: test.test_undo (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_undo
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/test/test_undo.py", line 7, in <module>
    import shapes
  File "/home/will/craftassist/python/craftassist/shapes.py", line 8, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


======================================================================
ERROR: test.test_with_model (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_with_model
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/will/craftassist/python/craftassist/test/test_with_model.py", line 8, in <module>
    import shapes
  File "/home/will/craftassist/python/craftassist/shapes.py", line 8, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'


----------------------------------------------------------------------
Ran 11 tests in 0.002s

FAILED (errors=11)
```

**Comment by MrAusnadian** [comment]
Figured it out. Needed to uninstall Python 2, reinstall Python 3.6, then fix the link and install 

```
sudo apt purge python2.7-minimal
sudo rm /usr/bin/python
sudo apt install python3
sudo ln -s /usr/bin/python3.6 /usr/bin/python
sudo apt install python3-pip
pip3 install numpy
python ./python/cuberite_process.py
```
